/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas_empleador;

import java.awt.Color;

/**
 *
 * @author Josue
 */
public class P_menu extends javax.swing.JFrame {
    

        int xMouse, yMouse;
    /**
     * Creates new form P_menu
     */
    public P_menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_fondo = new javax.swing.JPanel();
        P_barracontrol = new javax.swing.JPanel();
        P_salir = new javax.swing.JPanel();
        lbl_salir = new javax.swing.JLabel();
        lbl_maximizar = new javax.swing.JLabel();
        lbl_minimizar = new javax.swing.JLabel();
        P_head = new javax.swing.JPanel();
        lbl_bienvenida = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        P_home = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        P_barra = new javax.swing.JPanel();
        P_barra2 = new javax.swing.JPanel();
        P_ediInfo = new javax.swing.JPanel();
        lbl_modEmp = new javax.swing.JLabel();
        P_barrasalir = new javax.swing.JPanel();
        P_crearOferta = new javax.swing.JPanel();
        lbl_textocrearofer1 = new javax.swing.JLabel();
        lbl_crearOferta = new javax.swing.JLabel();
        P_cerrarsesion = new javax.swing.JPanel();
        lbl_cerrarsesion = new javax.swing.JLabel();
        lbl_iconouser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_fondo.setBackground(new java.awt.Color(225, 227, 229));
        P_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_barracontrol.setBackground(new java.awt.Color(253, 253, 253));
        P_barracontrol.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P_barracontrolMouseDragged(evt);
            }
        });
        P_barracontrol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P_barracontrolMousePressed(evt);
            }
        });
        P_barracontrol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_salir.setBackground(new java.awt.Color(253, 253, 253));
        P_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_salir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_salir.setForeground(new java.awt.Color(0, 0, 0));
        lbl_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_salir.setText("X");
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_salirMouseExited(evt);
            }
        });
        P_salir.add(lbl_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 20));

        P_barracontrol.add(P_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, -1, -1));

        lbl_maximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/Maximizar.png"))); // NOI18N
        lbl_maximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_maximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_maximizarMouseClicked(evt);
            }
        });
        P_barracontrol.add(lbl_maximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 30, 20));

        lbl_minimizar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_minimizar.setForeground(new java.awt.Color(0, 0, 0));
        lbl_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/Minimizar.png"))); // NOI18N
        lbl_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_minimizarMouseExited(evt);
            }
        });
        P_barracontrol.add(lbl_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 30, 20));

        P_fondo.add(P_barracontrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 20));

        P_head.setBackground(new java.awt.Color(161, 180, 212));
        P_head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bienvenida.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        lbl_bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bienvenida.setText("Bienvenido al Sistema de Bolsa de Empleos");
        P_head.add(lbl_bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1360, 50));

        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/Logo_miniatura_negativo.png"))); // NOI18N
        P_head.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 100));

        P_fondo.add(P_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1370, 100));

        Menu.setBackground(new java.awt.Color(161, 180, 212));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_home.setBackground(new java.awt.Color(161, 180, 212));
        P_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_home.setBackground(new java.awt.Color(255, 255, 255));
        lbl_home.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        lbl_home.setForeground(new java.awt.Color(0, 0, 0));
        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/icono home.png"))); // NOI18N
        lbl_home.setText("Inicio");
        lbl_home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_home.setIconTextGap(23);
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_homeMouseExited(evt);
            }
        });
        P_home.add(lbl_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        Menu.add(P_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        P_barra.setBackground(new java.awt.Color(0, 0, 153));
        P_barra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 51), null));
        P_barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Menu.add(P_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 10));

        P_barra2.setBackground(new java.awt.Color(0, 0, 153));
        P_barra2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 51), null));
        P_barra2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Menu.add(P_barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 10));

        P_ediInfo.setBackground(new java.awt.Color(161, 180, 212));
        P_ediInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_modEmp.setBackground(new java.awt.Color(255, 255, 255));
        lbl_modEmp.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        lbl_modEmp.setForeground(new java.awt.Color(0, 0, 0));
        lbl_modEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/icono editar.png"))); // NOI18N
        lbl_modEmp.setText("Editar Info de Cuenta");
        lbl_modEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_modEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_modEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_modEmpMouseExited(evt);
            }
        });
        P_ediInfo.add(lbl_modEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        Menu.add(P_ediInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 60));

        P_barrasalir.setBackground(new java.awt.Color(0, 0, 102));
        P_barrasalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        Menu.add(P_barrasalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 210, 10));

        P_fondo.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 590));

        P_crearOferta.setBackground(new java.awt.Color(204, 204, 204));
        P_crearOferta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_textocrearofer1.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        lbl_textocrearofer1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_textocrearofer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_textocrearofer1.setText("Opciones de Oferta Laboral");
        P_crearOferta.add(lbl_textocrearofer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 60));

        lbl_crearOferta.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        lbl_crearOferta.setForeground(new java.awt.Color(0, 0, 0));
        lbl_crearOferta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crearOferta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/crear_oferta-removebg-preview.png"))); // NOI18N
        lbl_crearOferta.setToolTipText("");
        lbl_crearOferta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_crearOferta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_crearOferta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_crearOferta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_crearOfertaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_crearOfertaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_crearOfertaMouseExited(evt);
            }
        });
        P_crearOferta.add(lbl_crearOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 210));

        P_fondo.add(P_crearOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 240, 210));

        P_cerrarsesion.setBackground(new java.awt.Color(161, 180, 212));
        P_cerrarsesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cerrarsesion.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        lbl_cerrarsesion.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/cerrar_sesion-removebg-preview.png"))); // NOI18N
        lbl_cerrarsesion.setText("Cerrar Sesión");
        lbl_cerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cerrarsesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_cerrarsesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_cerrarsesionMouseExited(evt);
            }
        });
        P_cerrarsesion.add(lbl_cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        P_fondo.add(P_cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 210, 60));

        lbl_iconouser.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        lbl_iconouser.setForeground(new java.awt.Color(0, 0, 0));
        lbl_iconouser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_iconouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_j/icono_usuario-removebg-preview.png"))); // NOI18N
        P_fondo.add(lbl_iconouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, 60));

        getContentPane().add(P_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void lbl_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseEntered
        // TODO add your handling code here:
        lbl_salir.setForeground(Color.WHITE);
        P_salir.setBackground(Color.red);
    }//GEN-LAST:event_lbl_salirMouseEntered

    private void lbl_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseExited
        // TODO add your handling code here:
        lbl_salir.setForeground(Color.BLACK);
        P_salir.setBackground(new Color(253, 253, 253));
    }//GEN-LAST:event_lbl_salirMouseExited

    private void lbl_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lbl_minimizarMouseClicked

    private void lbl_minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_minimizarMouseEntered

    private void lbl_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_minimizarMouseExited

    private void P_barracontrolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_barracontrolMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_P_barracontrolMousePressed

    private void P_barracontrolMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_barracontrolMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x -xMouse, y -yMouse);
    }//GEN-LAST:event_P_barracontrolMouseDragged

    private void lbl_crearOfertaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_crearOfertaMouseEntered
        // TODO add your handling code here:
        P_crearOferta.setBackground(new Color(27, 107, 184));
        lbl_textocrearofer1.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_lbl_crearOfertaMouseEntered

    private void lbl_crearOfertaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_crearOfertaMouseExited
        // TODO add your handling code here:
        P_crearOferta.setBackground(new Color(204, 204, 204));
        lbl_textocrearofer1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_crearOfertaMouseExited

    private void lbl_cerrarsesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarsesionMouseEntered
        // TODO add your handling code here:
        P_cerrarsesion.setBackground(new Color(225, 227, 229));
        lbl_cerrarsesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_cerrarsesionMouseEntered

    private void lbl_cerrarsesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarsesionMouseExited
        // TODO add your handling code here:
        P_cerrarsesion.setBackground(new Color(161, 180, 212));
    }//GEN-LAST:event_lbl_cerrarsesionMouseExited

    private void lbl_cerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarsesionMouseClicked
        // TODO add your handling code here:
        P_cerrarsesion.setBackground(new Color(202, 159, 78));
        lbl_cerrarsesion.setForeground(Color.BLACK);
        this.setVisible(false);
        P_bienvenida bienvenida = new P_bienvenida();
        bienvenida.setVisible(true);
    }//GEN-LAST:event_lbl_cerrarsesionMouseClicked

    private void lbl_crearOfertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_crearOfertaMouseClicked
        // TODO add your handling code here:
        lbl_textocrearofer1.setForeground(Color.BLACK);
        P_crearOferta.setBackground(new Color(202, 159, 78));
        //llamo al panel 
        JF_mostrarOfertas ofer = new JF_mostrarOfertas();
        ofer.setVisible(true);
    }//GEN-LAST:event_lbl_crearOfertaMouseClicked

    private void lbl_maximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_maximizarMouseClicked
        // TODO add your handling code here:
        //Para maximizar y volver a la normalidad
       /* if (this.getExtendedState() != P_menu.MAXIMIZED_BOTH) {
            this.setExtendedState(MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(NORMAL);
        }
*/
    }//GEN-LAST:event_lbl_maximizarMouseClicked

    private void lbl_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseEntered
        P_home.setBackground(new Color(225, 227, 229));
        lbl_home.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_homeMouseEntered

    private void lbl_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseExited
        P_home.setBackground(new Color(161, 180, 212));
        
    }//GEN-LAST:event_lbl_homeMouseExited

    private void lbl_modEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_modEmpMouseClicked
        P_modificaEmpleador m = new P_modificaEmpleador();
        m.setVisible(true);
    }//GEN-LAST:event_lbl_modEmpMouseClicked

    private void lbl_modEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_modEmpMouseEntered
        P_ediInfo.setBackground(new Color(225, 227, 229));
        lbl_modEmp.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_modEmpMouseEntered

    private void lbl_modEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_modEmpMouseExited
        P_ediInfo.setBackground(new Color(161, 180, 212));
    }//GEN-LAST:event_lbl_modEmpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel P_barra;
    private javax.swing.JPanel P_barra2;
    private javax.swing.JPanel P_barracontrol;
    private javax.swing.JPanel P_barrasalir;
    private javax.swing.JPanel P_cerrarsesion;
    private javax.swing.JPanel P_crearOferta;
    private javax.swing.JPanel P_ediInfo;
    private javax.swing.JPanel P_fondo;
    private javax.swing.JPanel P_head;
    private javax.swing.JPanel P_home;
    private javax.swing.JPanel P_salir;
    private javax.swing.JLabel lbl_bienvenida;
    private javax.swing.JLabel lbl_cerrarsesion;
    private javax.swing.JLabel lbl_crearOferta;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_iconouser;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_maximizar;
    private javax.swing.JLabel lbl_minimizar;
    private javax.swing.JLabel lbl_modEmp;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JLabel lbl_textocrearofer1;
    // End of variables declaration//GEN-END:variables
}
