/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Header;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.jdbc.Blob;
import com.mysql.jdbc.PreparedStatement;
import conexion.Conexion;
import controlador.Crtl_Hoja_vida;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import java.io.InputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.HojaVida;
import static vistas_empleador.JF_loginPostulante.cedula;

import java.awt.Image;

/**
 *
 * @author juanl
 */
public class CrearHojadeVida extends javax.swing.JPanel {

    Conexion mysql = new Conexion();
    Connection cn = mysql.conectar();
    Statement st;
    ResultSet rs;

    public FileInputStream fis;
    public int Bytes;

    String ruta;

    public CrearHojadeVida() {
        initComponents();
        traerImagen();
        llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_foto = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_genero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combo_estadoCivil = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_canton = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ciudad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_formacionAcademica = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_experiencia = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        txt_telefonoPersonal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcionProfesional = new javax.swing.JEditorPane();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_habilidades = new javax.swing.JEditorPane();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_adicional = new javax.swing.JEditorPane();
        jLabel14 = new javax.swing.JLabel();
        txt_nombreReferencia1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_telefonoReferencia1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_nombreReferencia2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_telefonoReferencia2 = new javax.swing.JTextField();
        btn_imprimir = new javax.swing.JButton();
        btn_guardar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(225, 227, 229));
        setPreferredSize(new java.awt.Dimension(1260, 810));

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FOTO");

        lbl_foto.setBackground(new java.awt.Color(153, 255, 255));
        lbl_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_foto.setFocusable(false);
        lbl_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_fotoMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Cédula");

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre completo");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Género");

        combo_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Femenino", "Masculino" }));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado civil");

        combo_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Soltero/a", "Casado/a", "Union libre", "Divorsiado/a", "Viudo/a" }));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantón resindencia");

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ciudad residencia");

        txt_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ciudadActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Dirección");

        jLabel12.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Formación academica");

        jLabel13.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Experiencia");

        jScrollPane1.setViewportView(txt_experiencia);

        jLabel8.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefóno personal");

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Corréo");

        jLabel10.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Descripción Profesional");

        jScrollPane2.setViewportView(txt_descripcionProfesional);

        jLabel18.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Habilidades");

        jScrollPane3.setViewportView(txt_habilidades);

        jLabel19.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Adicional");

        jScrollPane4.setViewportView(txt_adicional);

        jLabel14.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre apellido primera persona referencia");

        jLabel15.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("teléfono");

        jLabel16.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nombre apellidosegunda persona referencia");

        jLabel17.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Telefóno");

        btn_imprimir.setBackground(new java.awt.Color(27, 107, 184));
        btn_imprimir.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btn_imprimir.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
        btn_imprimir.setText(" Pdf");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_guardar1.setBackground(new java.awt.Color(27, 107, 184));
        btn_guardar1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btn_guardar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-guardar-50.png"))); // NOI18N
        btn_guardar1.setText("Guadar");
        btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar1ActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_grande.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_canton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(combo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(combo_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel20)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(31, 31, 31)
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txt_telefonoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(44, 44, 44)
                                                            .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(99, 99, 99)
                                                            .addComponent(jLabel1)))
                                                    .addGap(374, 374, 374)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_formacionAcademica, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(btn_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(105, 105, 105)
                                            .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_nombreReferencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(34, 34, 34)
                                        .addComponent(txt_telefonoReferencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_nombreReferencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addComponent(txt_telefonoReferencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_telefonoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(combo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(combo_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_canton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_formacionAcademica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txt_nombreReferencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txt_telefonoReferencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txt_nombreReferencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel19)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_telefonoReferencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_fotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_fotoMouseClicked
        // TODO add your handling code here:
        //Cargar imagen
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG ,PNG & GIF", "jpg", "GIF");
        chooser.setFileFilter(extensionFilter);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            ruta = chooser.getSelectedFile().getAbsolutePath();
            Image imagen = new ImageIcon(ruta).getImage();
            ImageIcon icono = new ImageIcon(imagen.getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), 0));
            lbl_foto.setIcon(icono);
        }
    }//GEN-LAST:event_lbl_fotoMouseClicked

    private void txt_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ciudadActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
        generarPdf();

    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar1ActionPerformed
        // TODO add your handling code here:
        HojaVida hoja = new HojaVida();
        Crtl_Hoja_vida controlHoja = new Crtl_Hoja_vida();

        //Cargar imagen
        //Insertar datos en la hoja de vida
        if (!txt_cedula.getText().isEmpty() && !txt_nombre.getText().isEmpty()
                && !txt_canton.getText().isEmpty() && !txt_ciudad.getText().isEmpty()
                && !txt_direccion.getText().isEmpty() && !txt_correo.getText().isEmpty() && !txt_descripcionProfesional.getText().isEmpty()
                && !txt_formacionAcademica.getText().isEmpty() && !txt_telefonoPersonal.getText().isEmpty() && !txt_telefonoReferencia1.getText().isEmpty()
                && !txt_telefonoReferencia2.getText().isEmpty() && !txt_nombreReferencia1.getText().isEmpty() && !txt_nombreReferencia2.getText().isEmpty()
                && !txt_habilidades.getText().isEmpty() && !txt_adicional.getText().isEmpty()) {

            hoja.setCedula(Integer.parseInt(txt_cedula.getText()));  //1
            hoja.setNombre(txt_nombre.getText());    //2
            hoja.setGenero((String) combo_genero.getSelectedItem()); //3
            hoja.setEstadoCivil((String) combo_estadoCivil.getSelectedItem()); //4
            hoja.setCanton(txt_canton.getText()); //5
            hoja.setCiudad(txt_ciudad.getText()); //6
            hoja.setDireccion(txt_direccion.getText()); //7
            hoja.setTelefonoPersonal(Integer.parseInt(txt_telefonoPersonal.getText())); //8
            hoja.setCorreo(txt_correo.getText()); //9
            hoja.setDescripcion(txt_descripcionProfesional.getText());  //10
            hoja.setFormacion(txt_formacionAcademica.getText());  //11
            hoja.setExperiencia(txt_experiencia.getText());  //12
            hoja.setTelreferencia1(Integer.parseInt(txt_telefonoReferencia1.getText())); //13
            hoja.setTelreferencia2(Integer.parseInt(txt_telefonoReferencia2.getText())); //14
            hoja.setNombreReferencia1(txt_nombreReferencia1.getText());  //15
            hoja.setNombreReferencia2(txt_nombreReferencia2.getText());  //16
            hoja.setHabilidades(txt_habilidades.getText()); //17
            hoja.setAdiccional(txt_adicional.getText()); //18
            hoja.setImagen(getImagen(ruta));

            if (controlHoja.CrearHojadeVida(hoja)) {
                JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese todos sus datos");
        }
    }//GEN-LAST:event_btn_guardar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JComboBox<String> combo_estadoCivil;
    private javax.swing.JComboBox<String> combo_genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JEditorPane txt_adicional;
    private javax.swing.JTextField txt_canton;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_ciudad;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JEditorPane txt_descripcionProfesional;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JEditorPane txt_experiencia;
    private javax.swing.JTextField txt_formacionAcademica;
    private javax.swing.JEditorPane txt_habilidades;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreReferencia1;
    private javax.swing.JTextField txt_nombreReferencia2;
    private javax.swing.JTextField txt_telefonoPersonal;
    private javax.swing.JTextField txt_telefonoReferencia1;
    private javax.swing.JTextField txt_telefonoReferencia2;
    // End of variables declaration//GEN-END:variables

    public byte[] getImagen(String ruta) {
        File imagen = new File(ruta);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream input = new FileInputStream(imagen);
            input.read(icono);
            return icono;

        } catch (Exception e) {
            return null;
        }
    }

    public void traerImagen() {
        cn = mysql.conectar();

        try {
            CallableStatement insertar = cn.prepareCall("{CALL sp_visualizarPostulaciones(?,?)}");
            insertar.setInt(1, 2);
            insertar.setInt(2, Integer.parseInt(cedula));
            rs = insertar.executeQuery();

            if (rs.next()) {
                java.sql.Blob blob = rs.getBlob(1);

                byte[] data = blob.getBytes(1, (int) blob.length());

                BufferedImage img = null;

                try {
                    img = ImageIO.read(new ByteArrayInputStream(data));
                } catch (Exception e) {
                    System.out.println("error " + e);
                }

                ImageIcon icono = new ImageIcon(img);
                int ancho = lbl_foto.getWidth() > 0 ? lbl_foto.getWidth() : 100;
                int alto = lbl_foto.getHeight() > 0 ? lbl_foto.getHeight() : 100;
                Icon imagen = new ImageIcon(icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
                lbl_foto.setIcon(imagen);
            }

        } catch (Exception e) {
            System.out.println("Error traer imagen " + e);
        }

    }

    public void llenarDatos() {

        try {

            CallableStatement insertar = cn.prepareCall("{CALL sp_visualizarPostulaciones(?,?)}");

            String ruta = System.getProperty("user.home");

            insertar.setInt(1, 1);
            insertar.setInt(2, Integer.parseInt(cedula));
            rs = insertar.executeQuery();

            while (rs.next()) {
                int cedulas = rs.getInt("post_cedula");  //1
                String nombreCompleto = rs.getString("hoj_NombreCompleto"); //2
                String genero = rs.getString("hoj_genero"); //3
                String estadoCivil = rs.getString("hoj_estadoCivil"); //4
                String canton = rs.getString("hoj_cantonResidencia"); //5
                String ciudad = rs.getString("hoj_cuidadResidencia");  //6
                String direccion = rs.getString("hoj_direccion"); //7
                int telPersonal = rs.getInt("hoj_telefonoPersonal"); //8
                String correo = rs.getString("hoj_direccion"); //9
                String descripcionPro = rs.getString("hoj_descripcionProfesional"); //10
                String formacion = rs.getString("hoj_formacionAcademica"); //11
                String Experiencia = rs.getString("hoj_Experiencia"); //12
                int telReferencia1 = rs.getInt("hoj_telRefencia1"); //13
                int telReferencia2 = rs.getInt("hoj_telReferencia2"); //14
                String NomReferencia1 = rs.getString("hoj_NombreReferencia1"); //15
                String NomReferencia2 = rs.getString("hoj_NombreReferencia2"); //16
                String habilidades = rs.getString("hoj_habilidades"); //17
                String adicional = rs.getString("hoj_adicional"); //18

                txt_cedula.setText(Integer.toString(cedulas));
                txt_nombre.setText(nombreCompleto);
                txt_telefonoPersonal.setText(Integer.toString(telPersonal));
                txt_canton.setText(canton);
                txt_ciudad.setText(ciudad);
                txt_direccion.setText(direccion);
                txt_correo.setText(correo);
                txt_descripcionProfesional.setText(descripcionPro);
                txt_formacionAcademica.setText(formacion);
                txt_experiencia.setText(Experiencia);
                txt_telefonoReferencia1.setText(Integer.toString(telReferencia1));
                txt_telefonoReferencia2.setText(Integer.toString(telReferencia2));
                txt_nombreReferencia1.setText(NomReferencia1);
                txt_nombreReferencia2.setText(NomReferencia2);
                txt_habilidades.setText(habilidades);
                txt_adicional.setText(adicional);

            }

            insertar.close();
            cn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }

    }

    public void generarPdf() {
        cn = mysql.conectar();

        Document documento = new Document(PageSize.A4);

        
        
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/HojaVida.pdf"));
            documento.open();

            Paragraph titulo2 = new Paragraph();
            titulo2.setAlignment(Paragraph.ALIGN_CENTER);
            titulo2.add("\n\n\n");
           
            // Obtener la imagen del método traerImagen()

            titulo2.setSpacingAfter(10f);
            documento.add(titulo2);

            try {
                CallableStatement insertar = cn.prepareCall("{CALL sp_visualizarPostulaciones(?,?)}");
                insertar.setInt(1, 2);
                insertar.setInt(2, Integer.parseInt(cedula));
                rs = insertar.executeQuery();

                if (rs.next()) {
                    java.sql.Blob blob = rs.getBlob(1);

                    byte[] data = blob.getBytes(1, (int) blob.length());

                
                    com.itextpdf.text.Image imagen = com.itextpdf.text.Image.getInstance(data);

                
                    float width = 150f;
                    float height = 200f;
                    imagen.scaleToFit(width, height );
                  
                    float centerX = PageSize.A4.getWidth() / 2;

              
                    float centerY = PageSize.A4.getHeight() - imagen.getScaledHeight();
 
                 
                
                    imagen.setAbsolutePosition(centerX - (width / 2), centerY);
                    Paragraph ima = new Paragraph();
                    ima.setAlignment(Paragraph.ALIGN_CENTER);
                    ima.add(imagen);
                    ima.setSpacingAfter(10f);
                    ima.add(imagen);
                    documento.add(ima);
                }

            } catch (Exception e) {
                System.out.println("Error traer imagen " + e);
            }
            
            
            
            Paragraph titulo3 = new Paragraph();
            titulo3.setAlignment(Paragraph.ALIGN_CENTER);
          
            titulo3.setFont(FontFactory.getFont("Calisto MT", 30, Font.NORMAL, BaseColor.BLUE));
            titulo3.add("\n\n\n\n\n\n\nHOJA DE VIDA\n");
            // Obtener la imagen del método traerImagen()

            titulo3.setSpacingAfter(10f);
            documento.add(titulo3);

            Paragraph titulo = new Paragraph();
            titulo.setAlignment(Paragraph.ALIGN_CENTER);
            titulo.setFont(FontFactory.getFont("Calisto MT", 14, Font.NORMAL, BaseColor.BLUE));
            titulo.add("---------------------------------------------------------------------------------------------------------------");
 

            titulo.setSpacingAfter(10f);
            documento.add(titulo);

            try {
                CallableStatement insertar = cn.prepareCall("{CALL sp_visualizarPostulaciones(?,?)}");
                insertar.setInt(1, 3);
                insertar.setInt(2, Integer.parseInt(cedula));
                rs = insertar.executeQuery();

                while (rs.next()) {
                    int cedulas = rs.getInt("post_cedula");
                    String nombreCompleto = rs.getString("hoj_NombreCompleto");
                    String genero = rs.getString("hoj_genero");
                    String estadoCivil = rs.getString("hoj_estadoCivil");
                    String canton = rs.getString("hoj_cantonResidencia");
                    String ciudad = rs.getString("hoj_cuidadResidencia");
                    String direccion = rs.getString("hoj_direccion");
                    int telPersonal = rs.getInt("hoj_telefonoPersonal");
                    String correo = rs.getString("hoj_correo");
                    String descripcionPro = rs.getString("hoj_descripcionProfesional");
                    String formacion = rs.getString("hoj_formacionAcademica");
                    String experiencia = rs.getString("hoj_Experiencia");
                    int telReferencia1 = rs.getInt("hoj_telRefencia1");
                    int telReferencia2 = rs.getInt("hoj_telReferencia2");
                    String nomReferencia1 = rs.getString("hoj_NombreReferencia1");
                    String nomReferencia2 = rs.getString("hoj_NombreReferencia2");
                    String habilidades = rs.getString("hoj_habilidades");
                    String adicional = rs.getString("hoj_adicional");

                    Paragraph parrafo = new Paragraph();
                    parrafo.setFont(FontFactory.getFont("Calisto MT", 14, Font.NORMAL, BaseColor.BLACK));
                    parrafo.add("\nCédula:\n" + cedulas + "\n");
                    parrafo.add("\nNombre completo: \n" + nombreCompleto + "\n");
                    parrafo.add("\nGénero: \n" + genero + "\n");
                    parrafo.add("\nEstado civil: \n" + estadoCivil + "\n");
                    parrafo.add("\nCantón de residencia \n" + canton + "\n");
                    parrafo.add("\nCiudad de residencia \n" + ciudad + "\n");
                    parrafo.add("\nDirección \n" + direccion + "\n");
                    parrafo.add("\nTeléfono personal \n" + telPersonal + "\n");
                    parrafo.add("\nCorreo electrónico \n" + correo + "\n");
                    parrafo.add("\nDescripción profesional \n" + descripcionPro + "\n");
                    parrafo.add("\nFormación académica \n" + formacion + "\n");
                    parrafo.add("\nExperiencia \n" + experiencia + "\n");
                    parrafo.add("\nNombre referencia 1 \n" + nomReferencia1 + "\n");
                    parrafo.add("\nTeléfono referencia 1 \n" + telReferencia1 + "\n");
                    parrafo.add("\nNombre referencia 2 \n" + nomReferencia2 + "\n");
                    parrafo.add("\nTeléfono referencia 2 \n" + telReferencia2 + "\n");
                    parrafo.add("\nHabilidades \n" + habilidades + "\n");
                    parrafo.add("\nAdicional \n" + adicional);

                    documento.add(parrafo);

                }
            } catch (SQLException e) {
                System.out.println("Error al cargar hoja de vida: " + e);
            }
            JOptionPane.showMessageDialog(null, "Hoja de vida creada correctamente");
            documento.close();
        } catch (FileNotFoundException | DocumentException e) {
            System.out.println("Error al generar PDF: " + e);
        }
    }

   
}
