/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controlador.PDFS;
import javax.swing.JOptionPane;

/**
 *
 * @author juanl
 */
public class ReportesPDF extends javax.swing.JPanel {

    /**
     * Creates new form ReportesPDF
     */
    public ReportesPDF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_carreras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_empleadores = new javax.swing.JButton();
        btn_postulantes = new javax.swing.JButton();

        setBackground(new java.awt.Color(225, 227, 229));
        setForeground(new java.awt.Color(225, 227, 229));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_miniatura.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reportes PDF");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Generar reportes lista de empleadores");

        btn_carreras.setBackground(new java.awt.Color(1, 53, 103));
        btn_carreras.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btn_carreras.setForeground(new java.awt.Color(255, 255, 255));
        btn_carreras.setText("Generar");
        btn_carreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carrerasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Generar reportes de carreras");

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Generar reportes de postulantes");

        btn_empleadores.setBackground(new java.awt.Color(1, 53, 103));
        btn_empleadores.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btn_empleadores.setForeground(new java.awt.Color(255, 255, 255));
        btn_empleadores.setText("Generar");
        btn_empleadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadoresActionPerformed(evt);
            }
        });

        btn_postulantes.setBackground(new java.awt.Color(1, 53, 103));
        btn_postulantes.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btn_postulantes.setForeground(new java.awt.Color(255, 255, 255));
        btn_postulantes.setText("Generar");
        btn_postulantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_postulantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(619, 619, 619)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(579, 579, 579)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel5)))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btn_empleadores, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280)
                .addComponent(btn_carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_postulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_postulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_empleadores, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 343, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_empleadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadoresActionPerformed
        // TODO add your handling code here:
        PDFS empleadores = new PDFS();
        empleadores.ReporteEmpleadores();
        JOptionPane.showMessageDialog(null, "Dirigase al escritorio ");
    }//GEN-LAST:event_btn_empleadoresActionPerformed

    private void btn_carrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carrerasActionPerformed
        // TODO add your handling code here:
        PDFS carreras = new PDFS();
        carreras.ReporteCarreras();
        JOptionPane.showMessageDialog(null, "Dirigase al escritorio ");
    }//GEN-LAST:event_btn_carrerasActionPerformed

    private void btn_postulantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_postulantesActionPerformed
        // TODO add your handling code here:
        PDFS ofertas = new PDFS();
        ofertas.ReportePostulantes();
        JOptionPane.showMessageDialog(null, "Dirigase al escritorio ");
        
    }//GEN-LAST:event_btn_postulantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_carreras;
    private javax.swing.JButton btn_empleadores;
    private javax.swing.JButton btn_postulantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
